"use client";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
import { RequireAuth, useAuth } from "@/lib/auth-context";
import { deleteById, listCompanies, saveCredentialValue, upsertCompany } from "@/lib/firestore";
import { useEffect, useState } from "react";
import { Company } from "@/types";
const initial = { name:"", industry:"", interestLevel:3, status:"興味あり", myPageUrl:"", loginId:"", loginPassword:"", memo:"", lastCheckedAt:"" };
function Content(){const { user } = useAuth(); const [rows,setRows]=useState<(Company & {id:string})[]>([]); const [form,setForm]=useState(initial); const [showPw,setShowPw]=useState(false); const refresh=async()=>user&&setRows(await listCompanies(user.uid)); useEffect(()=>{refresh();},[user]); if(!user) return null; return <div className="min-h-screen md:flex"><Sidebar/><main className="flex-1 p-4 space-y-4"><h1 className="text-xl font-bold">企業一覧</h1><form className="bg-white p-4 rounded grid md:grid-cols-2 gap-2" onSubmit={async(e)=>{e.preventDefault(); await upsertCompany({...form,userId:user.uid,createdAt:new Date().toISOString(),loginPassword:saveCredentialValue(form.loginPassword)}); setForm(initial); refresh();}}><input placeholder="企業名" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="業界" value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})}/><input type="number" min={1} max={5} value={form.interestLevel} onChange={e=>setForm({...form,interestLevel:Number(e.target.value)})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Company['status']})}><option>興味あり</option><option>応募済み</option><option>選考中</option><option>内定</option><option>お祈り</option></select><input placeholder="マイページURL" value={form.myPageUrl} onChange={e=>setForm({...form,myPageUrl:e.target.value})}/><input placeholder="ログインID" value={form.loginId} onChange={e=>setForm({...form,loginId:e.target.value})}/><div className="flex gap-2"><input type={showPw?"text":"password"} placeholder="ログインパスワード" value={form.loginPassword} onChange={e=>setForm({...form,loginPassword:e.target.value})}/><button type="button" onClick={()=>setShowPw(!showPw)}>{showPw?"非表示":"表示"}</button></div><input type="date" value={form.lastCheckedAt} onChange={e=>setForm({...form,lastCheckedAt:e.target.value})}/><textarea placeholder="メモ" value={form.memo} onChange={e=>setForm({...form,memo:e.target.value})}/><button className="bg-blue-600 text-white rounded px-4 py-2">追加</button></form><div className="grid md:grid-cols-2 gap-3">{rows.map(c=><div key={c.id} className="bg-white rounded p-3 shadow"><Link href={`/companies/${c.id}`} className="font-semibold">{c.name}</Link><p>{c.industry} / {c.status}</p><button className="text-red-500" onClick={async()=>{await deleteById('companies',c.id); refresh();}}>削除</button></div>)}</div></main></div>}
export default function CompaniesPage(){return <RequireAuth><Content/></RequireAuth>;}
